function graphe_resp_stocks(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 12-Oct-2010 11:08:04

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1);
hold('all');

% Create plot
plot(X1,Y1,'Color',[1 0 0]);

% Create light
light('Parent',axes1,'Position',[-0.0004811 1 0.001667]);

% Create line
annotation(figure1,'line',[0.8881 0.8881],[0.1088 0.9244]);

% Create line
annotation(figure1,'line',[0.1299 0.9049],[0.1098 0.7992]);

% Create line
annotation(figure1,'line',[0.5174 0.5174],[0.1086 0.9242]);

% Create doublearrow
annotation(figure1,'doublearrow',[0.5194 0.8868],[0.418 0.4192]);

% Create textbox
annotation(figure1,'textbox','String',{'Valeurs admissibles'},...
    'FontName','Serif',...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'Position',[0.6646 0.3766 0.1069 0.03646]);

